"""initial tables

Revision ID: a5607d65d680
Revises: 
Create Date: 2026-02-28 12:22:11.484725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5607d65d680'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('synthea_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('admit_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('mechanism_of_injury', sa.String(), nullable=False),
    sa.Column('iss', sa.Integer(), nullable=True),
    sa.Column('los', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=True),
    sa.Column('note_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('encounter_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('primary_diagnosis_code', sa.String(), nullable=True),
    sa.Column('primary_diagnosis_desc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('source_note_id', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('field_label', sa.String(), nullable=False),
    sa.Column('field_key', sa.String(), nullable=False),
    sa.Column('extracted_value', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('source_note_type', sa.String(), nullable=True),
    sa.Column('conflict_reason', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_note_id'], ['clinical_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extraction_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('corrected_value', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decisions')
    op.drop_table('extractions')
    op.drop_table('encounters')
    op.drop_table('clinical_notes')
    op.drop_table('patients')
    # ### end Alembic commands ###
